### ISSUE TITLE
Node As usual

### ISSUE THREAD

**Issue by chillingchakra** [OpenSourceTreasure/Deepist#1]
I gotta say, every time I try to do anything with NodeJS and it's tools, like NVM and NPM and all this stuff, it never works, I can't even run a server. There is no load command, or capitalized Load, for sure there is no Load. so I try npm load, and nvm load and then nodejs load and none of it works, I figure I'm missing a package because as usual, with node you have to manage these versions and all this crap..

Well so I install http-server, because I find it on the internet,  and they say, it's a simple server, and yes it is. it runs, on port 8080 and then I get UFW, the uncomplicated firewall to unblock 8080, but it doesn't matter, none of it works, eventually I figure out I need some crap called yarn, I don't know. There are no dependencies, I mean there are the three, and after you install a bunch of others, it kinda works, but never to the end. Why? because it's Node. It never works because it's Node, because it has versions, and even after you install this thing
npm install -g auto-install
which is supposed to be able to get everything for you, you end up with 354 packages instead of 9. Why because it's Node, and even after you get every package in the world, if you have that much space on your computer, it probably wont work, because it's Node.

**Comment by chillingchakra** [comment]
I wanted to also say thanks for the great idea, I appreciate the screenshot. I'll try to find something similar.

**Comment by OpenSourceTreasure** [comment]
I built this with Nodejs, Bootstrap and Summernote. I know those are the 3 necessary dependencies. What I do is create a directory, and open Terminal in that directory, and then install NodeJS and Bootstrap (or whatever). I'm on Windows.
Try out the Demo of Deepist, and give it a star if you like it! [chillingchakra](https://github.com/chillingchakra)
https://opensourcetreasure.github.io/Deepist/index.html

**Comment by OpenSourceTreasure** [comment]
npm - run this from Terminal - npm install -g npm
Nodejs - https://nodejs.org/en - download it from the main page, link is prominently displayed on the left.

Once I did this, I was able to really get into the magic of Github! 🎸

I hope this helps you [chillingchakra](https://github.com/chillingchakra)
